# Generated by Django 5.0.7 on 2024-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_category_title_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
