# Generated by Django 5.0.6 on 2024-08-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
    ]
